definitions:
  ensweb.BaseResponse:
    properties:
      message:
        type: string
      status:
        type: boolean
    type: object
  ensweb.PublicKeyResponse:
    properties:
      message:
        type: string
      publicKey:
        type: string
      status:
        type: boolean
    type: object
  server.AddDeviceRequest:
    properties:
      publicKey:
        type: string
      serialNumber:
        type: string
    type: object
  server.DeviceRequest:
    properties:
      serialNumber:
        type: string
    type: object
  server.DeviceStatus:
    properties:
      isBlocked:
        type: boolean
      message:
        type: string
      serialNumber:
        type: string
      status:
        type: boolean
    type: object
  server.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  server.LoginResponse:
    properties:
      message:
        type: string
      status:
        type: boolean
      token:
        type: string
    type: object
  server.UserRequest:
    properties:
      isPinRequired:
        type: boolean
      maxNumFingers:
        type: integer
      serialNumber:
        type: string
      uid:
        type: string
      username:
        type: string
    type: object
  server.UserResponse:
    properties:
      message:
        type: string
      status:
        type: boolean
      token:
        type: string
      userStatus:
        $ref: '#/definitions/server.UserStatus'
    type: object
  server.UserStatus:
    properties:
      allowedFingers:
        type: integer
      enrolledFingers:
        type: integer
      isPinRequired:
        type: boolean
      pin:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/adddevice:
    post:
      consumes:
      - application/json
      description: Add multiple devices.
      parameters:
      - description: Array of AddDeviceRequest objects
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.AddDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.DeviceRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: Add Device
      tags:
      - Devices
  /api/adminlogin:
    post:
      consumes:
      - application/json
      description: Authenticate an administrator.
      parameters:
      - description: JSON object containing login credentials
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: Admin Login
  /api/blockdevice:
    post:
      consumes:
      - application/json
      description: Block a device by serial number.
      parameters:
      - description: JSON object containing serial number of the device to block
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.DeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.DeviceRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: Block Device
      tags:
      - Devices
  /api/devicestatus:
    post:
      consumes:
      - application/json
      description: Get the status of a device by serial number.
      parameters:
      - description: JSON object containing serial number of the device to check status
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.DeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.DeviceRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.DeviceStatus'
      summary: Get Device Status
  /api/fingerenrolled:
    post:
      consumes:
      - application/json
      description: Update the finger enrolled status of a user.
      parameters:
      - description: JSON object containing user details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: User FingerEnrolled Status
  /api/getpublickey:
    get:
      consumes:
      - application/json
      description: Get the public key of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ensweb.PublicKeyResponse'
      summary: Get the public key of the server
      tags:
      - general
  /api/keyadded:
    post:
      consumes:
      - application/json
      description: Update the user registration status to indicate whether the key
        is added.
      parameters:
      - description: JSON object containing user details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: Update User Registration Status
  /api/resetuser:
    post:
      consumes:
      - application/json
      description: Reset a user by removing their data and updating enrollment status.
      parameters:
      - description: JSON object containing user details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: Reset User
  /api/setnumfingers:
    post:
      consumes:
      - application/json
      description: Set the maximum number of fingers allowed for a user.
      parameters:
      - description: JSON object containing user details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: SetNumFingers
  /api/setpinrequired:
    post:
      consumes:
      - application/json
      description: Set whether PIN is required for a user.
      parameters:
      - description: JSON object containing user details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: SetPinRequired
  /api/unblockdevice:
    post:
      consumes:
      - application/json
      description: Unblock a device by serial number.
      parameters:
      - description: JSON object containing serial number of the device to unblock
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.DeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.DeviceRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: Unblock Device
      tags:
      - Devices
  /api/userlogin:
    post:
      consumes:
      - application/json
      description: Authenticate and log in a user.
      parameters:
      - description: JSON object containing user login details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ensweb.BaseResponse'
      summary: User Login
swagger: "2.0"
